# Site settings
title: The Well-Read Catholic
description: Pick it up and read
owner: Patrick Callahan # or company name
first_published: 2018 # if migrating another site, the year of your first publish
email: info@wellreadcathlic.com
baseurl: "/index" # the subpath of your site, e.g. /blog
url: "wellreadcatholic.com" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/wellreadcathlic
  #github: https://github.com/<username>
  #linkedin-square: https://linkedin.com/in/<username>
  facebook-official: https://facebook.com/wellreadcatholic
  #google-plus-square: https://plus.google.com/u/0/+<username>
  #email: /contact/
  #flickr:
  instagram: https://instagram.com/wellreadcatholic
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  soundcloud: https://soundcloud.com/wellreadcatholic
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
